# Producer config
producer_config:
  output_filename: "random_producer2.csv"
  num_columns: 288
  wait_time: 1.0
#  port: COM5
 
# Consumer config
consumer_config:
  nrows: 10
  col_indices: [1,null]  # Use first 3 columns
  file_names: ["random_producer2.csv"]
  plot_kwargs:
    # label: "Sensor Average"
    color: "green"
    marker: "x"
    linestyle: "-"
    linewidth: 1.0
    markersize: 4
    alpha: 0.7
  # x_values: [100,500,800]
  title: "Environmental Sensors Running Mean"
  xlabel: "Columns"
  ylabel: "Mean Value"